### ISSUE TITLE
InvalidRequest on Bing AI on Multigpt

### ISSUE THREAD

**Issue by gamer20088** [SingularityLabs-ai/MultiGPT-mini#2]
When I try chatting with bing it says, "InvalidRequest."

**Comment by ishandutta2007** [comment]
@gamer20088 are you sure you are logged into bing? I would suggest first login to bing. reload the bing page. Try the bing chat directly once. then return to MultiGPT. Let me know if you are still getting the same error.

By the way thanks for pointing out even for stale login states we should make our error message more clear and helpful.

**Comment by gamer20088** [comment]
@ishandutta2007 Very odd, not working.

**Comment by Ironcock** [comment]
I have the same error

**Comment by ishandutta2007** [comment]
@gamer20088  @Ironcock we found the issue, fixes for bing have been released to chrome webstore. Update (or resinstal) to latest version 0.0.9

**Comment by Ironcock** [comment]
Bing still has InvalidRequest in Vivaldi. Probably because Vivaldi is using spoofing to pretend being Edge to access Bing AI.

**Comment by ishandutta2007** [comment]
@Ironcock for the time being we are not looking to support vivaldi. You don't need edge or vivaldi to access bing, you can use MultiGPT in chrome/brave.

**Comment by Ironcock** [comment]
Yea I know that I dont need it, but Vivaldi is my primary browser for years. I guess I have to figure something out myself. Thank you

**Comment by ishandutta2007** [comment]
@Ironcock Thanks for understanding. In case you have a secondary browser too which happens to be chrome which you might be using from time to time, fell free to suggest new ideas to incorporate into multiGPT. We would be happy to discuss if we come across interesting feature requests.

**Comment by gamer20088** [comment]
@ishandutta2007 yesterday it was working on brave browser but now I am getting the same error.

**Comment by ishandutta2007** [comment]
@gamer20088 it works for us. 
- which country are you in ? (maybe we should test from vpm of that country)
- Can you fully uninstall and reinstall ?(don't press update)

**Comment by gamer20088** [comment]
@ishandutta2007 I redownloaded it yesterday and bing ai was working, but now, a day later, the same error is coming up. I am on Brave Browser in the US.

**Comment by ishandutta2007** [comment]
@gamer20088 we have found the issue on windows and are working on it(for mac it is fine). @everyone Next time around while reporting any issue please do mention OS,County,Browser with respective version numbers upfront so that it becomes easier for us to hunt it down.

**Comment by gamer20088** [comment]
@ishandutta2007 Any guess when it will be fixed?

**Comment by ishandutta2007** [comment]
@ishandutta2007  can you test it again from your end. It has been fixed in our last release, we tested with US IPs for both windows and MacOS and it seemed fine. Just reinstall the latest version.

**Comment by gamer20088** [comment]
@ishandutta2007 Bing still does not work. For some reason when I reinstall, it only works on the first day, and then it is back to saying 'InvalidRequest'

**Comment by ishandutta2007** [comment]
@gamer20088 we haven't been able to reproduce it, we tried both edge/chrome for both windows and mac using USA IP, everything seems fine. From our end we will keep the fight on.

From your end you can try couple of things. First you make sure you are on version 0.0.12 by going to the settings page. Here is the settings button 
![settings](https://github.com/SingularityLabs-ai/MultiGPT-mini/assets/2527354/d63d8cf2-7a11-49bb-b38d-e42aff1171d9)

Once ensured that, next if your day to day work don't require saved cookies, you can try clearing browser cookies and relogin all the required chatbots again.

**Comment by ishandutta2007** [comment]
@gamer20088  Hey just clarifying once again did you get `ServiceClient failure`, we haven't been able to reproduce it yet from our end but another of our user said he got `ServiceClient failure`

**Comment by gamer20088** [comment]
@ishandutta2007 Nope, I get invalidrequest

**Comment by ishandutta2007** [comment]
@gamer20088  I know you mentioned you are on windows, but we couldn't reproduce on windows yet, but we rolled out some changed regarding bing for mac and linux users. Can you check if it solved yours or not ?

**Comment by gamer20088** [comment]
@ishandutta2007 Wow,  just opened my computer up and it seems like it is working right now!
